dist: xenial
sudo: true
before_install:
  - curl http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.18.2-1.linux-64.sh > install.sh
  - sudo sh install.sh --batch
install:
  - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
  - sudo apt-get install chktex
script:
  - make
  - chktex -W # Print version information.
  - chktex -q -n 6 *.lytex 2>/dev/null| tee lint.out    # If lint output is non-empty report an error.
  - chktex -q -n 6 text/*.lytex 2>/dev/null| tee -a lint.out   # If lint output is non-empty report an error.
  - test ! -s lint.out